"""adds Moon  model

Revision ID: 78390cda9a93
Revises: 
Create Date: 2022-11-04 08:06:14.026635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78390cda9a93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('distance_from_planet', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('planet', sa.Column('moon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planet', 'moon', ['moon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'moon_id')
    op.drop_table('moon')
    # ### end Alembic commands ###
