"""empty message

Revision ID: d4b7986ed272
Revises: 1fb331adf524
Create Date: 2022-11-10 13:24:50.768463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b7986ed272'
down_revision = '1fb331adf524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moon', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'moon', 'planet', ['planet_id'], ['id'])
    op.drop_constraint('planet_moon_id_fkey', 'planet', type_='foreignkey')
    op.drop_column('planet', 'moon_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('moon_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('planet_moon_id_fkey', 'planet', 'moon', ['moon_id'], ['id'])
    op.drop_constraint(None, 'moon', type_='foreignkey')
    op.drop_column('moon', 'planet_id')
    # ### end Alembic commands ###
